# Generated by Django 3.1.4 on 2020-12-06 04:52

from django.db import migrations

def create_data(apps, schema_editor):
    Room = apps.get_model('rooms', 'Room')
    Room(name="Entry",description="Entry room", width=5, height=5, floor="dirt")

class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
